"""adding device properties to engagement

Revision ID: 27f205401f42
Revises: 1ebd5c23446f
Create Date: 2024-11-21 19:34:03.354914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27f205401f42'
down_revision = '1ebd5c23446f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('engagements', sa.Column('device_os', sa.String(length=100), nullable=True))
    op.add_column('engagements', sa.Column('device_browser', sa.String(length=100), nullable=True))
    op.add_column('engagements', sa.Column('device_type', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('engagements', 'device_type')
    op.drop_column('engagements', 'device_browser')
    op.drop_column('engagements', 'device_os')
    # ### end Alembic commands ###
